name: Wiki Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build wiki
      run: npm run docs:build

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: docs/.vuepress/dist
        key: ${{ runner.os }}-build-cache-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore build cached
        uses: actions/cache/restore@v3
        with:
          path: docs/.vuepress/dist
          key: ${{ runner.os }}-build-cache-${{ github.sha }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
          fqdn: wiki2.inxiny.cn
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
